### ISSUE TITLE
finally is not a function

### ISSUE THREAD

**Issue by Jacobsolawetz** [roboflow-ai/server-benchmark#1]
`(node:30987) UnhandledPromiseRejectionWarning: TypeError: infer(...).finally is not a function`

causing inference to only run on a single image in `images`

the whole folder worked for me when I changed to `.then` on line 35 - can PR if @yeldarby you think it's benign for other node versions

**Comment by yeldarby** [comment]
What version of Node are you on? `finally` was introduced to Promises in Node 10 (and [Node 12 is the oldest maintained version](https://nodejs.org/en/about/releases/) currently)

`.then` isn't the same as `.finally` (it only runs on `resolve` whereas `finally` runs on both `resolve` and `reject`)

**Comment by Jacobsolawetz** [comment]
looks like I was on node v8 on the train server - works when I upgraded to n 12

And nice, i see you already dropped a note about node version there in the requirements section
